# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingularity < Formula
  desc "Single-binary internet-connectivity monitor."
  homepage "https://github.com/pingular/pingularity"
  version "0.1.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "ce8278ad07e83d7eb7461e148a2b05e943a020aef692f1d4c1d4fcd3575e0bdf"

      define_method(:install) do
        bin.install "pingularity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "4d301c817543f8c8753072d1525eebd8f2a791e23622ad5d7f1d38971edeaac5"

      define_method(:install) do
        bin.install "pingularity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "20cd60071a2667970e64f969bd9cc4164f4643cef5e40b63496e4c36135c79ed"
      define_method(:install) do
        bin.install "pingularity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "f5dc684eeabe13014cf6cb365edf1eb8dba9d42af160fd6afb7702c6e4e68e35"
      define_method(:install) do
        bin.install "pingularity"
      end
    end
  end

  def caveats
    <<~EOS
      To run pingularity as a background service via launchd, run:
        sudo pingularity install
    EOS
  end
end
