# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingularity < Formula
  desc "Single-binary internet-connectivity monitor."
  homepage "https://github.com/pingular/pingularity"
  version "0.1.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "74eb1e25becd52bd8f1526e19c814866b73029605b24576b097af589905f4e96"

      define_method(:install) do
        bin.install "pingularity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "9aad98741ced9cbdbe7d810f796a6b2157c3c1343b25b90308bbd4b150df86a8"

      define_method(:install) do
        bin.install "pingularity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "0fb3bb2226f2260c14a5911d387d07309ec9fac2c5fd0c9f392023cc9c800e9f"
      define_method(:install) do
        bin.install "pingularity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "f1da5282811dab88e8ba5276b12ee302c03cbb5645097acff4dd225a1dab1832"
      define_method(:install) do
        bin.install "pingularity"
      end
    end
  end

  def caveats
    <<~EOS
      To run pingularity as a background service via launchd, run:
        sudo pingularity install
    EOS
  end
end
