# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingularity < Formula
  desc "Single-binary internet-connectivity monitor."
  homepage "https://github.com/pingular/pingularity"
  version "0.1.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_darwin_amd64.tar.gz"
      sha256 "88cda59c96c3f596a42bf1457e6baac3f0195d13a017bc4640f78df559e1385f"

      define_method(:install) do
        bin.install "pingularity"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_darwin_arm64.tar.gz"
      sha256 "12fc44456e8d56d9f5e9287fe4ebf48df6edac2350d65990c98c4d9dc6cf1619"

      define_method(:install) do
        bin.install "pingularity"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_linux_amd64.tar.gz"
      sha256 "261646068d89322a17fe1ed27a9ac6f7079b4cf03ffe055d4eaaf36828da014b"
      define_method(:install) do
        bin.install "pingularity"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pingular/pingularity/releases/download/v0.1.0-rc1/pingularity_0.1.0-rc1_linux_arm64.tar.gz"
      sha256 "b09d4b46744546e593a1211778dd85db40d1625508e8dd558063f5ed0d7811df"
      define_method(:install) do
        bin.install "pingularity"
      end
    end
  end

  def caveats
    <<~EOS
      To run pingularity as a background service via launchd, run:
        sudo pingularity install
    EOS
  end
end
