# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingularity" do
  version "0.57.0"

  on_macos do
    on_intel do
      sha256 "c19d04d0ce6e50694cc0b7dc11e50d53d934a2c28c6fb9fc069b71643361650d"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b87fc02503d7751edb3f6e7bc9f0ddfbf9892eeccda99a65eeb006b470289d2"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5f665311063ba6ae052a40e8d3f937b4e2f38769e52f9b4ff04cc56ca3933650"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddf343fb2f50ab6912146c1a2e9b9a238dab884e509e0953fc65fe2c4d06d580"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pingularity"
  desc "Single-binary internet-connectivity monitor."
  homepage "https://github.com/pingular/pingularity"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pingularity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pingularity"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To run pingularity as a background service via launchd, run:
      sudo pingularity install
  EOS
end
