# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingularity" do
  version "0.61.3"

  on_macos do
    on_intel do
      sha256 "66230decf9a187ed8a4fb231538123036850a7a763d0ea8b546e9983071fe71c"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6c567f570f79f313903a5f233483804c6dc0c22ad93d818055d59ac5a7333043"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c005d406731da41bf433493ec07fa4086fa85475bac49bf2367e2bee531c0866"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6606a96461ef8efea93f192c0cd6c5df3e48618d257d6b37bee24f683e0eef1"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pingularity"
  desc "Single-binary internet-connectivity monitor."
  homepage "https://github.com/pingular/pingularity"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pingularity"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pingularity"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    To run pingularity as a background service via launchd, run:
      sudo pingularity install
  EOS
end
