# This file was generated by GoReleaser. DO NOT EDIT.
cask "pingularity" do
  depends_on macos: :ventura

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/pingularity"], must_succeed: false
    end
  end

  version "0.100.4"

  on_macos do
    on_intel do
      sha256 "854298d6b8fea128259ebdd511c848d0eef64be97c6235d37b0b471d2d21b867"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a506b0ffa3db177e838c3371411b0427fcc5845f77a2369a2f12c96655fa527"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a04044dbeef86346f14035fe1e537291ce6dccfe0c55dcbc086613eae323349"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1bb74fe5a644061f1d481b26679b740eb355baa35ae43d97116b4e976398991e"
      url "https://github.com/pingular/pingularity/releases/download/v#{version}/pingularity_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pingularity"
  desc "Single-binary internet-connectivity monitor."
  homepage "https://github.com/pingular/pingularity"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pingularity"

  # No zap stanza required

  caveats <<~EOS
    To run pingularity as a background service via launchd, run:
      sudo pingularity install
    If that service is already installed, switch it to this version with:
      sudo pingularity restart
  EOS
end
